### ISSUE TITLE
Multiple Categories (low prio)

### ISSUE THREAD

**Issue by jkrug** [ongr-io/demo.ongr.io#164]
Products should be assigned in diferent Categories (which is possible) and should show the correct breadcrumb path.

**Comment by saimaz** [comment]
This is a good topic. We cannot add such a functionality in any bundle. So this is pure document structure implementation in the Demo. The thing is if we could do like this, then you won't have example how to use Demo in a simple way. Also, as an example for the new projects, this Demo will be very complex. To support breadcrumbs for multiple categories requires some custom logic.
